apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: postgres-service
        - name: USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        volumeMounts:
        - name: odoo-storage
          mountPath: /var/lib/odoo
        securityContext:
          runAsUser: 0
      volumes:
      - name: odoo-storage
        persistentVolumeClaim:
          claimName: odoo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
  - protocol: TCP
    port: 8069
    targetPort: 8069
    nodePort: 31050
